[MNIST]
train_img = "data/train-images.idx3-ubyte"
train_label = "data/train-labels.idx1-ubyte"
test_img = "data/t10k-images.idx3-ubyte"
test_label = "data/t10k-labels.idx1-ubyte"
train_size = 60000
test_size = 10000

[hyper_parameters]
iterations = 10000
batch_size = 100
learning_rate = 0.01
